### ISSUE TITLE
Empty depend libopusfile0

### ISSUE THREAD

**Issue by varlesh** [fantoro/openspades-ppa-issues#1]
Ubuntu Xenial (but need fix that for all Series).
**LOG:**
`./openspades-bin: error while loading shared libraries: libopusfile.so.0: cannot open shared object file: No such file or directory`

**Comment by fantoro** [comment]
Thanks for helping but I stopped maintaining the ppa, I am not competent enough to actually maintain it, there's always a way for launchpad to find an error and I don't know how to fix it most of the time.
