### ISSUE TITLE
hardcoded Icons & install on hicolor icon theme directory

### ISSUE THREAD

**Issue by varlesh** [fantoro/openspades-ppa-issues#2]
It's freedesktop standard!
On `rules `need add install paths this files to `/usr/share/icons/hicolor` directory.
And upload original desktop file icon name:
https://github.com/yvt/openspades/blob/master/Resources/Unix/Desktop/openspades.desktop
```
[Desktop Entry]
Version=1.0
Type=Application
Terminal=false
Exec=openspades %U
Name=OpenSpades
GenericName=Sandbox building and FPS videogame
Comment=Open-source clone of Ace of Spades
Keywords=game;fps;sandbox;voxel;aos;
Icon=openspades
Categories=Game;ActionGame;
MimeType=x-scheme-handler/aos;
```
**Icon=openspades**

Also add `StartupWMClass=openspades-bin`

**Comment by fantoro** [comment]
Thanks for helping but I stopped maintaining the ppa, I am not competent enough to actually maintain it, there's always a way for launchpad to find an error and I don't know how to fix it most of the time.
